# Generated by Django 4.2.29 on 2026-04-16 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('descripcion', models.TextField()),
                ('color', models.CharField(default='#1565C0', help_text='Color HEX para la UI', max_length=7)),
                ('icono', models.CharField(default='📚', max_length=4)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Competencia',
                'verbose_name_plural': 'Competencias',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('titulo', models.CharField(max_length=160)),
                ('descripcion', models.CharField(max_length=300)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveles', to='competencias.competencia')),
            ],
            options={
                'verbose_name': 'Nivel',
                'verbose_name_plural': 'Niveles',
                'ordering': ['numero'],
                'unique_together': {('competencia', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='competencias.nivel')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=300)),
                ('correcta', models.BooleanField(default=False)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='competencias.pregunta')),
            ],
            options={
                'verbose_name': 'Opción',
                'verbose_name_plural': 'Opciones',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('cuerpo', models.TextField(help_text='Texto principal de la lección')),
                ('ejemplo', models.TextField(blank=True, help_text='Ejemplo concreto para el niño')),
                ('tip', models.CharField(blank=True, help_text='Tip rápido o frase memorable', max_length=300)),
                ('nivel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contenido', to='competencias.nivel')),
            ],
            options={
                'verbose_name': 'Contenido',
                'verbose_name_plural': 'Contenidos',
            },
        ),
        migrations.CreateModel(
            name='ResultadoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correctas', models.PositiveSmallIntegerField(default=0)),
                ('total', models.PositiveSmallIntegerField(default=0)),
                ('completado', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='competencias.nivel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_competencias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resultado de usuario',
                'verbose_name_plural': 'Resultados de usuarios',
                'ordering': ['-actualizado'],
                'unique_together': {('usuario', 'nivel')},
            },
        ),
    ]
