# Generated by Django 6.0.3 on 2026-04-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='actividades',
            field=models.TextField(blank=True, help_text='Mini-actividades sugeridas para el alumno (HTML permitido)'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='faq',
            field=models.TextField(blank=True, help_text='Preguntas frecuentes y respuestas (HTML permitido)'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='video_file',
            field=models.FileField(blank=True, help_text='Video educativo local (MP4, WebM, etc)', null=True, upload_to='videos/%Y/%m/'),
        ),
    ]
